[package]
name = "vulkano_boids_simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
rfd = "0.16.0"
vulkano = "0.35.2"
winit = { version = "0.30.12", features = [ "rwh_06" ]}

